package com.zstronics.ceibro.base

const val name = "name"
const val FRAGMENT_CLASS = "fragment_class"
const val SHOW_TOOLBAR = "_show_toolbar"
const val HOME_AS_UP_INDICATOR = "_home_as_up_indicator"
const val EXTRA = "_bundle_extras"
const val BUNDLE_EXTRA = "_my_bundle_extras"
const val TYPE_EXTRA = "_type_extras"
const val EXTRA_FROM_NOTIFICATION = "_bundle_extras_notifications"
const val TOOLBAR_TITLE = "toolbar_title"
const val INDEX = "_index"

// SharedPreference  Keys

const val KEY_USERNAME: String = "USERNAME"
const val KEY_IS_USER_LOGGED_IN: String = "KEY_IS_USER_LOGGED_IN"
const val KEY_USER = "_USER"
const val KEY_SAVED_TASK = "_SAVED_TASK"
const val KEY_DRAWING_OBJ = "_DRAWING_OBJ"
const val KEY_TOKEN = "_TOKEN"
const val KEY_USER_NAME = "_USER_NAME"
const val KEY_PASS = "_USER_PASS"
const val KEY_SECURE_UUID = "_SECURE_UUID"
const val KEY_DEVICE_TYPE = "_DEVICE_TYPE"
const val KEY_ANDROID_ID = "_ANDROID_ID"
const val KEY_SOCKET_OBSERVER_SET = "_SOCKET_OBSERVER_SET"
const val KEY_USER_EMAIL = "_USER_EMAIL"
const val KEY_ID = "_ID"
const val KEY_PROJECT = "_PROJECT"
const val KEY_IS_FIRST_TIME_LAUNCH = "_KEY_IS_FIRST_TIME_LAUNCH"
const val KEY_IS_TO_ME_UNREAD = "KEY_IS_TO_ME_UNREAD"
const val KEY_IS_FROM_ME_UNREAD = "KEY_IS_FROM_ME_UNREAD"
const val KEY_IS_HIDDEN_UNREAD = "KEY_IS_HIDDEN_UNREAD"
const val KEY_SYNCED_CONTACTS = "_KEY_SYNCED_CONTACTS"
const val KEY_DATA_SYNC_UPDATED_AT = "_KEY_DATA_SYNC_UPDATED_AT"
const val KEY_INBOX_UPDATED_AT = "_KEY_INBOX_UPDATED_AT"
const val KEY_CONTACTS_CURSOR = "_KEY_CONTACTS_CURSOR"
const val KEY_TOKEN_VALID = "_KEY_TOKEN_VALID"
const val KEY_APP_FIRST_RUN_FOR_INTERNET = "_KEY_APP_FIRST_RUN"
const val KEY_LAST_OFFLINE = "_KEY_LAST_OFFLINE"
const val KEY_updatedAndNewContacts = "_updatedAndNewContacts"
const val KEY_User_Last_Login_Time = "_KEY_User_Last_Login_Time"
