package com.zstronics.ceibro.ui.enums

enum class EventType {
    SEND_MESSAGE,
    RECEIVE_MESSAGE,
    REFRESH_CHAT,
    MESSAGE_DELIVERED,
    ALL_MESSAGE_READ,
    UNREAD_MESSAGE_COUNT,
    MESSAGE_SEEN,
    USER_JOINED_ROOM,
    USER_LEFT_ROOM,
    FAV_CHAT,
    PIN_MESSAGE,
    DELETE_CHAT_ROOM,
    ADD_USER_TO_CHAT,
    REMOVE_USER_FROM_CHAT,
    ADD_GROUP_TO_CHAT,
    REMOVE_GROUP_FROM_CHAT,
    LEAVE_CHAT_ROOM,
    ALL_MESSAGE_SEEN
}