name: Create Release and Upload Artifacts

on:
  push:
    branches: [ "main" ]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Create Ceibro Debug Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          body: |
            Changes in this Release:
            - Bug fixes
            - Enhancements
          draft: false
          prerelease: false

      - name: Upload APK to Release
        uses: actions/upload-artifact@v2
        with:
          name: Ceibro Debug
          path: app/build/outputs/apk/dev/debug/app-dev-debug.apk

#      - name: Ceibro Release Created
#        run: |
#          echo "Ceibro Release ${{ steps.create_release.outputs.release_id }} created"
#          echo "https://github.com/${{ github.repository }}/releases/tag/${{ steps.create_release.outputs.tag_name }}"

