name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Get Update
      run: sudo apt-get update
    - name: Install Snapd
      run: sudo apt-get install snapd
    - name: Install slacktee
      run: sudo snap install slacktee
      
    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Send APK to Slack
      run: |
        apk_path=$(find . -name "*.apk")
        slacktee --config slacktee.conf -p #ceibro-github-mobile -f $apk_path

        slack-cli -f $apk_path -c #ceibro-github-mobile
